- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Downgrade Docker to 1.12
  apt:
    name: docker=1.12
    force: yes
    state: present
