- name: Allow Docker to be accessible from the outside
  lineinfile:
    dest: /etc/systemd/system/docker.service.d/overlay.conf
    regexp: '^(ExecStart.*dockerd.*?)(\s*-H tcp://.*:2375\s*)?$'
    # Disable iptables for Docker 1.13
    line: '\1 -H tcp://{{ inventory_hostname }}:2375'
    backrefs: true
    state: present
  register: result
  notify:
    - restart docker

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed
