- name: iptables | Install iptables support package
  apt:
    name: iptables-persistent
    force: yes
    state: present

- name: iptables | Get iptables rules
  shell: iptables -L
  register: iptablesrules
  check_mode: no
 
- block:
   
  - name: iptables | Add flannel iptable rules (in)
    command: /sbin/iptables -A FORWARD -i cni0 -j ACCEPT -m comment --comment "CNI-Forward-Fix"

  - name: iptables | Add flannel iptable rules (out)
    command: /sbin/iptables -A FORWARD -o cni0 -j ACCEPT -m comment --comment "CNI-Forward-Fix"

  - name: iptables | Save iptables
    shell: iptables-save > /etc/iptables/rules.v4

  when: iptablesrules.stdout.find("CNI-Forward-Fix") == -1
 
