- name: Copy init file for kubeadm
  copy: src=kubeadm.yml dest=/etc/kuberentes/kubeadm.yml mode=0755

- name: Run kubeadm init on master
  # --skip-preflight-checks until the new Docker SE version numbers are supported
  command: kubeadm init --token {{ kubeadm_token }} --service-cidr {{ network.service_subnet }} --pod-network-cidr={{ network.pod_subnet }} --skip-preflight-checks
  register: kubeadm_init

# - debug: var=kubeadm_init.stdout

- name: Copy flannel installation
  template: src=kube-flannel.yml dest=/etc/kubernetes/kube-flannel.yml

- name: Create flannel resources
  command: kubectl create -f /etc/kubernetes/kube-flannel.yml

- name: Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true

- name: Rename cluster configuration
  local_action: command mv {{ playbook_dir }}/run/admin.conf {{ playbook_dir }}/run/pi-cluster.cfg
